name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Run Mdoc
        run: sbt mdoc
      - name: Setup Node
        working-directory: ./website
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        working-directory: ./website
        run: yarn --cwd website install --frozen-lockfile
      - name: Build Website
        working-directory: ./website
        run: yarn --cwd website build
      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./website
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
